modLoader="javafml"
loaderVersion="[44,45)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/raulsmartin/Food-Expansion/issues"
showAsResourcePack=false

[[mods]]
    modId="foodexpansion"
    version="${file.jarVersion}"
    displayName="Food Expansion: Reimagined"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/food-expansion-reimagined"
    logoFile="logo.png"
    credits="Thanks to Lellson for his original Food Expansion."
    authors="raulsmartin & Simple Dimple"
    description="Adds various food into the game"

    [[dependencies.foodexpansion]]
        modId="forge"
        mandatory=true
        versionRange="[44,45)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.foodexpansion]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19.3,1.19.4)"
        ordering="NONE"
        side="BOTH"